name: mentor
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=0.13.0=pyhd3eb1b0_0
  - anyio=3.5.0=py38h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - attrs=24.2.0=py38h06a4308_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.2.0=h27d5ac6_0
  - brotli-bin=1.2.0=h1421c7b_0
  - brotli-python=1.0.9=py38h6a678d5_8
  - ca-certificates=2025.12.2=h06a4308_0
  - click=8.1.7=py38h06a4308_0
  - cloudpickle=3.0.0=py38h06a4308_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cytoolz=0.12.2=py38h5eee18b_0
  - dask-core=2023.4.1=py38h06a4308_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.14.1=hf5b9546_0
  - fsspec=2024.6.1=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jpeg=9f=h5ce9db8_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.23.0=py38h06a4308_0
  - jsonschema-specifications=2023.7.1=py38h06a4308_0
  - jupyter-packaging=0.7.12=pyhd3eb1b0_0
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - jupyter_server=1.23.4=py38h06a4308_0
  - jupyterlab=3.0.14=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py38h06a4308_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libpng=1.6.54=hee55ce4_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.5.1=hffd6297_1
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=2.0.4=py38h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - nbclassic=0.5.5=py38h06a4308_0
  - nbclient=0.8.0=py38h06a4308_0
  - nbconvert=7.16.4=py38h06a4308_0
  - nbformat=5.10.4=py38h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - networkx=3.1=py38h06a4308_0
  - notebook-shim=0.2.3=py38h06a4308_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=24.1=py38h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - partd=1.4.1=py38h06a4308_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py38h5eee18b_0
  - pip=21.1.3=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_1
  - platformdirs=3.10.0=py38h06a4308_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - pytz=2024.1=py38h06a4308_0
  - pywavelets=1.4.1=py38h5eee18b_0
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py38h06a4308_0
  - requests=2.32.3=py38h06a4308_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - scikit-image=0.18.1=py38ha9443f7_0
  - scipy=1.9.3=py38h14f4228_1
  - send2trash=1.8.2=py38h06a4308_0
  - setuptools=75.1.0=py38h06a4308_0
  - sniffio=1.3.0=py38h06a4308_0
  - soupsieve=2.5=py38h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - terminado=0.17.1=py38h06a4308_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - toolz=0.12.0=py38h06a4308_0
  - tornado=6.4.1=py38h5eee18b_0
  - traitlets=5.14.3=py38h06a4308_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - urllib3=2.2.3=py38h06a4308_0
  - webencodings=0.5.1=py38_1
  - websocket-client=1.8.0=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - addict==2.4.0
      - aioice==0.9.0
      - aiortc==1.9.0
      - ale-py==0.10.1
      - antlr4-python3-runtime==4.8
      - appdirs==1.4.4
      - asttokens==3.0.1
      - autolab-core==1.1.1
      - autolab-perception==1.0.0
      - av==12.3.0
      - avp-stream==2.51
      - beautifulsoup4==4.14.3
      - blinker==1.8.1
      - certifi==2026.1.4
      - cffi==1.17.0
      - charset-normalizer==3.4.4
      - colorlog==6.10.1
      - comm==0.2.3
      - configargparse==1.7.1
      - cryptography==46.0.4
      - cvxopt==1.3.2
      - cycler==0.12.1
      - cython==0.29.37
      - dash==3.3.0
      - deprecated==1.3.1
      - dill==0.4.0
      - dm-control==1.0.8
      - dm-env==1.6
      - dm-tree==0.1.8
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - etils==1.3.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fasteners==0.15
      - fastjsonschema==2.21.2
      - ffmpeg-python==0.2.0
      - filelock==3.16.1
      - flask==3.0.3
      - flatten-dict==0.4.2
      - free-mujoco-py==2.1.6
      - future==1.0.0
      - gdown==5.2.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glfw==2.10.0
      - google-auth==2.48.0
      - google-auth-oauthlib==1.0.0
      - google-crc32c==1.5.0
      - grasp-nms==1.0.2
      - graspnetapi==1.2.11
      - grpcio==1.70.0
      - grpcio-tools==1.48.2
      - gym==0.23.0
      - gym-notices==0.1.0
      - gymnasium==0.29.1
      - h11==0.16.0
      - h5py==3.11.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.1.0
      - hydra-submitit-launcher==1.1.5
      - idna==3.11
      - ifaddr==0.2.0
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.4
      - iniconfig==2.1.0
      - ipdb==0.13.9
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.16
      - labmaze==1.0.6
      - lazy-loader==0.4
      - lxml==6.0.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.4.2
      - mdurl==0.1.2
      - meshcat==0.3.2
      - monotonic==1.6
      - mpmath==1.3.0
      - mujoco==2.3.0
      - mujoco-py==2.1.2.14
      - multiprocess==0.70.18
      - narwhals==1.42.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - omegaconf==2.1.2
      - open3d==0.19.0
      - opencv-python==4.7.0.72
      - pandas==1.3.0
      - parso==0.8.5
      - pathtools==0.1.2
      - plotly==6.5.0
      - pluggy==1.5.0
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - pure-eval==0.2.3
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pydub==0.25.1
      - pyee==13.0.0
      - pygame==2.6.1
      - pylibsrtp==0.10.0
      - pyngrok==7.2.12
      - pyopengl==3.1.10
      - pyopenssl==25.3.0
      - pyquaternion==0.9.9
      - pyserial==3.5
      - pytest==8.3.5
      - pywavefront==1.3.3
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - requests-oauthlib==2.0.0
      - retrying==1.4.2
      - rich==14.3.1
      - rsa==4.9.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.8
      - scikit-learn==1.3.2
      - sentry-sdk==2.51.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - stable-baselines3==2.4.1
      - stack-data==0.6.3
      - submitit==1.5.4
      - sympy==1.13.3
      - tb-nightly==2.14.0a20230808
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==1.1.0
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - tomli==2.4.0
      - torch==2.4.1
      - torchvision==0.13.1+cu116
      - tqdm==4.67.1
      - transforms3d==0.3.1
      - trimesh==4.10.1
      - triton==3.0.0
      - typeguard==4.4.0
      - typer-slim==0.20.1
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - u-msgpack-python==2.8.0
      - wandb==0.15.1
      - wcwidth==0.2.14
      - websockets==13.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - yapf==0.31.0
prefix: /home/cuhk/miniconda3/envs/mentor
