wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/test_lx/DMC/dmc_test.py
    python_version: 3.8.20
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1769674493.489615
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 13
      - 22
      - 23
      - 35
      4: 3.8.20
      5: 0.15.1
      8:
      - 5
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.SACPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''use_sde'': False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 500000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1769674499250036992
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/d72b0sf1
_last_obs:
  desc: null
  value: "[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  4.1521999e-01  4.7616491e-01\n   0.0000000e+00  0.0000000e+00\
    \  1.0000000e+00  0.0000000e+00\n   0.0000000e+00  1.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   1.0000000e+00 -3.7337217e-01  1.7824174e+00  0.0000000e+00\n\
    \  -4.5634089e+00 -4.6343750e-08 -1.1263494e+01 -3.7337235e-01\n   1.5485533e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n  -5.8782405e-01 -1.4305981e-04\
    \  3.1589810e-04  2.3714204e-04\n  -1.4305886e-04 -3.1595983e-04  2.3714200e-04\
    \ -7.1791670e-04\n  -2.3323549e-03  1.7308042e-03 -7.1791641e-04  2.3323521e-03\n\
    \   1.7308036e-03  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  2.6609039e-01 -4.6073928e-01  6.7925572e-01\n   3.2553828e-01 -3.9331999e-01\
    \  2.8908134e-01  9.0159214e-01\n  -1.4803342e-02 -8.3492434e-01 -2.9681158e-01\
    \  8.4464645e-01\n  -9.5599627e-01  4.6476355e-01 -6.1565858e-01  9.4314885e-01\n\
    \  -7.8192192e-01  9.6925032e-01  2.0893936e-01 -9.6750325e-01\n  -9.2093670e-01\
    \  1.2658267e-01 -5.1373833e-01 -1.6836885e-01\n   7.8846431e-01  4.4482026e-01\
    \ -4.9534684e-01 -4.3143716e-01\n   2.6103511e-01 -2.7264297e-01  8.2417881e-01\
    \ -3.2712781e-01\n  -6.5734506e-01  2.9921317e-01 -7.4465066e-01  6.6481560e-01\n\
    \  -8.7358586e-02 -6.7451604e-02 -2.4856344e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7911421d9670>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (223,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (38,), float32)
n_envs:
  desc: null
  value: 1
buffer_size:
  desc: null
  value: 100000
batch_size:
  desc: null
  value: 256
learning_starts:
  desc: null
  value: 100
tau:
  desc: null
  value: 0.005
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x7911421d96d0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -38.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.0003\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x7911424bc9d0>
policy:
  desc: null
  value: "SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n\
    \      (0): Linear(in_features=223, out_features=256, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n\
    \    )\n    (mu): Linear(in_features=256, out_features=38, bias=True)\n    (log_std):\
    \ Linear(in_features=256, out_features=38, bias=True)\n  )\n  (critic): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n  )\n)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=223,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n  )\n  (mu): Linear(in_features=256,\
    \ out_features=38, bias=True)\n  (log_std): Linear(in_features=256, out_features=38,\
    \ bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x79113d5abe80>
