wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/test_lx/DMC/dmc_test.py
    python_version: 3.8.20
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1769674750.556033
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 13
      - 22
      - 23
      - 35
      4: 3.8.20
      5: 0.15.1
      8:
      - 5
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.SACPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''use_sde'': False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 500000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1769674755631469294
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/bbewijad
_last_obs:
  desc: null
  value: "[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n\
    \   0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \  0.0000000e+00  4.1521999e-01  4.7616491e-01\n   0.0000000e+00  0.0000000e+00\
    \  1.0000000e+00  0.0000000e+00\n   0.0000000e+00  1.0000000e+00  0.0000000e+00\
    \  0.0000000e+00\n   1.0000000e+00 -6.4282829e-01 -4.6722543e-01  0.0000000e+00\n\
    \  -4.5846400e+00 -3.8759168e-08 -1.1272314e+01 -6.4282846e-01\n  -7.7234894e-01\
    \  0.0000000e+00 -0.0000000e+00  0.0000000e+00\n  -7.6693696e-01 -2.5967820e-04\
    \  4.4756345e-04  6.2273932e-04\n  -2.5967654e-04 -4.4767058e-04  6.2273926e-04\
    \ -9.5110986e-04\n  -2.1036665e-03  2.2041958e-03 -9.5110940e-04  2.1036621e-03\n\
    \   2.2041951e-03  0.0000000e+00  0.0000000e+00  0.0000000e+00\n   0.0000000e+00\
    \ -8.5562438e-01 -3.3531174e-01 -3.8766232e-01\n   2.2715189e-01  6.9048887e-01\
    \  5.7628429e-01  5.9318304e-01\n   3.3206217e-02  4.8909450e-01  1.1939878e-01\
    \ -2.2369865e-01\n   4.7235468e-01  9.1660120e-02 -3.4282041e-01 -9.1449505e-01\n\
    \   7.4421436e-01  8.3113849e-01 -8.7871665e-01 -7.1354526e-01\n   9.3074298e-01\
    \  5.3339702e-01 -9.3392724e-01  3.9791530e-01\n   1.7984092e-01  8.5569549e-01\
    \  6.3285106e-01 -4.5998558e-01\n   1.9907153e-01 -3.7779099e-01  4.8403600e-01\
    \ -6.7581236e-01\n  -1.8199769e-01 -8.6708790e-01 -8.8782930e-01  7.9344082e-01\n\
    \  -2.3289861e-01 -8.5997766e-01  9.2897063e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7262780d0940>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (223,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (38,), float32)
n_envs:
  desc: null
  value: 1
buffer_size:
  desc: null
  value: 100000
batch_size:
  desc: null
  value: 256
learning_starts:
  desc: null
  value: 100
tau:
  desc: null
  value: 0.005
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x7262780d09a0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -38.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.0003\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x72627817c9d0>
policy:
  desc: null
  value: "SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n\
    \      (0): Linear(in_features=223, out_features=256, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n\
    \    )\n    (mu): Linear(in_features=256, out_features=38, bias=True)\n    (log_std):\
    \ Linear(in_features=256, out_features=38, bias=True)\n  )\n  (critic): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n\
    \    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n    )\n  )\n)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=223,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n  )\n  (mu): Linear(in_features=256,\
    \ out_features=38, bias=True)\n  (log_std): Linear(in_features=256, out_features=38,\
    \ bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=261,\
    \ out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256,\
    \ out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256,\
    \ out_features=1, bias=True)\n  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x72627352cb80>
